version: 0.2
        
phases:
  install:
    run-as: root
    on-failure: ABORT 
    runtime-versions:
      python: 3.10
  build:
    on-failure: ABORT
    commands:
      - pip install opencv-python
      - pip install -r requirements.txt
      - python3 run_app.py
