"""empty message

Revision ID: 40ec49f70481
Revises: fd0bcc7cd2ac
Create Date: 2023-02-18 23:37:31.098613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40ec49f70481'
down_revision = 'fd0bcc7cd2ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogger', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ResetString', sa.String(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_blogger_ResetString'), ['ResetString'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogger', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_blogger_ResetString'), type_='unique')
        batch_op.drop_column('ResetString')

    # ### end Alembic commands ###
