"""empty message

Revision ID: dd14a579a3a5
Revises: aeadd3f18b5c
Create Date: 2023-02-16 04:28:09.761076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd14a579a3a5'
down_revision = 'aeadd3f18b5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume_image', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('resume_file', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.drop_column('resume_file')
        batch_op.drop_column('resume_image')

    # ### end Alembic commands ###
