"""empty message

Revision ID: fd0bcc7cd2ac
Revises: dd14a579a3a5
Create Date: 2023-02-17 01:22:50.788063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd0bcc7cd2ac'
down_revision = 'dd14a579a3a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.drop_column('Name')

    op.create_table('settings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('Recipient_name', sa.VARCHAR(), nullable=True),
    sa.Column('Recipient_mail', sa.VARCHAR(), nullable=True),
    sa.Column('Sendinblue_Api_Key', sa.VARCHAR(), nullable=True),
    sa.Column('setting_uuid', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_settings'),
    sa.UniqueConstraint('Recipient_mail', name='uq_settings_Recipient_mail'),
    sa.UniqueConstraint('Recipient_name', name='uq_settings_Recipient_name'),
    sa.UniqueConstraint('Sendinblue_Api_Key', name='uq_settings_Sendinblue_Api_Key'),
    sa.UniqueConstraint('setting_uuid', name='uq_settings_setting_uuid')
    )
    # ### end Alembic commands ###
